Categories:
  - Education
  - Security
License: GPL-3.0-or-later
AuthorName: Association TUTODECODE
AuthorWebSite: https://tutodecode.org
WebSite: https://tutodecode.org
SourceCode: https://github.com/TUTODECODE-FR/TUTODECODE
IssueTracker: https://github.com/TUTODECODE-FR/TUTODECODE/issues
Changelog: https://github.com/TUTODECODE-FR/TUTODECODE/releases
AutoName: TUTODECODE
RepoType: git
Repo: https://github.com/TUTODECODE-FR/TUTODECODE.git
Builds:
  - versionName: 1.0.2
    versionCode: 19
    commit: v1.0.2
    sudo:
      - apt-get update || apt-get update
      - apt-get install -y openjdk-17-jdk
    srclibs:
      - flutter@stable
    rm:
      - ios
      - linux
      - macos
      - web
      - windows
    prebuild:
      - flutterVersion=$(cat .flutter-version)
      - '[[ $flutterVersion ]]'
      - git -C $$flutter$$ checkout -f $flutterVersion
      - export PUB_CACHE=$(pwd)/.pub-cache
      - $$flutter$$/bin/flutter config --no-analytics
      - $$flutter$$/bin/flutter pub get
    scanignore:
      - $$flutter$$/bin/cache
    scandelete:
      - .pub-cache
    build:
      - export PUB_CACHE=$(pwd)/.pub-cache
      - export FDROID_BUILD=true
      - $$flutter$$/bin/flutter build apk --release --no-tree-shake-icons
    output: build/app/outputs/flutter-apk/app-release.apk

AutoUpdateMode: Version
UpdateCheckMode: Tags ^v[0-9]+\.[0-9]+\.[0-9]+$
UpdateCheckData: pubspec.yaml|version:\s.+\+(\d+)|.|version:\s(.+)\+
CurrentVersion: 1.0.2
CurrentVersionCode: 19
