include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: false
    strict-inference: false
    strict-raw-types: false
  errors:
    missing_required_param: error
    missing_return: error
    avoid_print: warning
    close_sinks: error
    cancel_subscriptions: error
    unrelated_type_equality_checks: error
    avoid_empty_else: error
    no_duplicate_case_values: error

linter:
  rules:
    - avoid_print
    - close_sinks
    - cancel_subscriptions
    - throw_in_finally
    - unrelated_type_equality_checks
    - avoid_empty_else
    - avoid_relative_lib_imports
    - avoid_web_libraries_in_flutter
    - control_flow_in_finally
    - empty_statements
    - no_duplicate_case_values
    - valid_regexps
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - unnecessary_statements
    - prefer_void_to_null
    - unawaited_futures
    - no_literal_bool_comparisons
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_iterable_whereType


