include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - close_sinks
    - cancel_subscriptions
    - throw_in_finally
    - unrelated_type_equality_checks
    - avoid_empty_else
    - avoid_relative_lib_imports
    - control_flow_in_finally
    - empty_statements
    - no_duplicate_case_values
    - valid_regexps
