sonar.projectKey=TUTODECODE-FR_T2DECODE
sonar.organization=tutodecode-fr


# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=T2DECODE
#sonar.projectVersion=1.0


# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.sources=lib
sonar.tests=test

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8

sonar.dart.lcov.reportPaths=coverage/lcov.info
sonar.exclusions=landing_page/**, android/**, ios/**, macos/**, linux/**, windows/**, web/**
sonar.coverage.exclusions=lib/features/**/screens/**, lib/features/**/widgets/**, lib/features/lab/simulators/**, lib/widgets/**, lib/core/widgets/**, lib/features/**/service/**, lib/utils/**, lib/features/*/lab_catalog.dart, lib/features/*/tool_catalog.dart, lib/main.dart, **/*.g.dart, **/*.freezed.dart
sonar.cpd.exclusions=lib/features/**/screens/**, lib/features/**/widgets/**, lib/features/lab/simulators/**, lib/widgets/**
