// SPDX-License-Identifier: GPL-3.0-only
// Copyright (C) 2024-2025 TUTODECODE Association <contact@tutodecode.org>

import 'dart:convert';

/// Parser for the TDC Domain-Specific Language (.tdc files generated by TDC-SDK).
/// Converts TDC DSL declarative syntax into a standard Course Map.
class TdcDslParser {
  /// Checks if the content conforms to the TDC DSL syntax.
  static bool isTdcDsl(String content) {
    final trimmed = content.trim();
    return trimmed.contains(RegExp(r'\bcourse\s+["a-zA-Z0-9_-]+\s*\{'));
  }

  /// Parses TDC DSL content and returns a standard Course Map compatible with Course.fromMap.
  static Map<String, dynamic> parse(String source) {
    final tokens = _tokenize(source);
    final parser = _DslParser(tokens);
    return parser.parseCourse();
  }

  static List<_Token> _tokenize(String source) {
    final tokens = <_Token>[];
    int i = 0;
    final len = source.length;

    while (i < len) {
      final c = source[i];

      // Whitespace
      if (c == ' ' || c == '\t' || c == '\r' || c == '\n') {
        i++;
        continue;
      }

      // Comments (# or //)
      if (c == '#' || (c == '/' && i + 1 < len && source[i + 1] == '/')) {
        while (i < len && source[i] != '\n') {
          i++;
        }
        continue;
      }

      // Triple quoted string """ ... """ or ''' ... '''
      if (i + 2 < len &&
          ((c == '"' && source[i + 1] == '"' && source[i + 2] == '"') ||
              (c == "'" && source[i + 1] == "'" && source[i + 2] == "'"))) {
        final quoteChar = c;
        final quoteStr = quoteChar * 3;
        i += 3;
        final start = i;
        while (i + 2 < len &&
            !(source[i] == quoteChar &&
                source[i + 1] == quoteChar &&
                source[i + 2] == quoteChar)) {
          i++;
        }
        final strVal = source.substring(start, i);
        if (i + 2 < len) i += 3; // consume closing quotes
        tokens.add(_Token(_TokenType.string, _dedent(strVal)));
        continue;
      }

      // Single line string "..." or '...'
      if (c == '"' || c == "'") {
        final quoteChar = c;
        i++;
        final sb = StringBuffer();
        while (i < len && source[i] != quoteChar) {
          if (source[i] == '\\' && i + 1 < len) {
            i++;
            final next = source[i];
            if (next == 'n') {
              sb.write('\n');
            } else if (next == 't') {
              sb.write('\t');
            } else if (next == 'r') {
              sb.write('\r');
            } else {
              sb.write(next);
            }
          } else {
            sb.write(source[i]);
          }
          i++;
        }
        if (i < len) i++; // consume closing quote
        tokens.add(_Token(_TokenType.string, sb.toString()));
        continue;
      }

      // Punctuation
      if (c == '{') {
        tokens.add(_Token(_TokenType.braceOpen, '{'));
        i++;
        continue;
      }
      if (c == '}') {
        tokens.add(_Token(_TokenType.braceClose, '}'));
        i++;
        continue;
      }
      if (c == ':') {
        tokens.add(_Token(_TokenType.colon, ':'));
        i++;
        continue;
      }
      if (c == '[') {
        tokens.add(_Token(_TokenType.bracketOpen, '['));
        i++;
        continue;
      }
      if (c == ']') {
        tokens.add(_Token(_TokenType.bracketClose, ']'));
        i++;
        continue;
      }
      if (c == ',') {
        tokens.add(_Token(_TokenType.comma, ','));
        i++;
        continue;
      }

      // Identifiers / unquoted values (words, numbers, durations like 15min, 1h, etc.)
      final start = i;
      while (i < len &&
          source[i] != ' ' &&
          source[i] != '\t' &&
          source[i] != '\r' &&
          source[i] != '\n' &&
          source[i] != '{' &&
          source[i] != '}' &&
          source[i] != ':' &&
          source[i] != '[' &&
          source[i] != ']' &&
          source[i] != ',' &&
          source[i] != '#' &&
          source[i] != '"' &&
          source[i] != "'") {
        i++;
      }
      final raw = source.substring(start, i);
      tokens.add(_Token(_TokenType.identifier, raw));
    }

    return tokens;
  }

  static String _dedent(String text) {
    // Normalise trim whitespace on edges of multiline string
    var lines = text.split('\n');
    if (lines.isNotEmpty && lines.first.trim().isEmpty) {
      lines = lines.sublist(1);
    }
    if (lines.isNotEmpty && lines.last.trim().isEmpty) {
      lines = lines.sublist(0, lines.length - 1);
    }
    return lines.join('\n');
  }
}

enum _TokenType {
  string,
  identifier,
  braceOpen,
  braceClose,
  colon,
  bracketOpen,
  bracketClose,
  comma,
}

class _Token {
  final _TokenType type;
  final String value;
  _Token(this.type, this.value);

  @override
  String toString() => '${type.name}($value)';
}

class _DslParser {
  final List<_Token> tokens;
  int _pos = 0;

  _DslParser(this.tokens);

  _Token? get _current => _pos < tokens.length ? tokens[_pos] : null;
  _Token? get _next => _pos + 1 < tokens.length ? tokens[_pos + 1] : null;

  _Token _consume() {
    final t = _current;
    if (t == null) throw Exception('Fin inattendue du fichier TDC');
    _pos++;
    return t;
  }

  bool _match(_TokenType type, [String? value]) {
    if (_current == null) return false;
    if (_current!.type != type) return false;
    if (value != null && _current!.value != value) return false;
    return true;
  }

  _Token _expect(_TokenType type, [String? value]) {
    if (!_match(type, value)) {
      throw Exception(
          'Erreur de syntaxe TDC: attendu $type ${value ?? ''}, reçu ${_current?.type} "${_current?.value}"');
    }
    return _consume();
  }

  Map<String, dynamic> parseCourse() {
    _expect(_TokenType.identifier, 'course');
    final courseId = _consume().value;
    _expect(_TokenType.braceOpen, '{');

    String title = courseId;
    String description = '';
    String category = 'general';
    String level = 'beginner';
    String duration = '1h';
    String icon = 'BookOpen';
    List<String> keywords = ['EXTERNAL'];
    final chapters = <Map<String, dynamic>>[];

    while (!_match(_TokenType.braceClose) && _current != null) {
      if (_match(_TokenType.identifier, 'module')) {
        chapters.add(_parseModule());
      } else if (_match(_TokenType.identifier, 'title')) {
        _consume();
        _optionalColon();
        title = _parseValueAsString();
      } else if (_match(_TokenType.identifier, 'description')) {
        _consume();
        _optionalColon();
        description = _parseValueAsString();
      } else if (_match(_TokenType.identifier, 'category')) {
        _consume();
        _optionalColon();
        category = _parseValueAsString();
      } else if (_match(_TokenType.identifier, 'level')) {
        _consume();
        _optionalColon();
        level = _parseValueAsString();
      } else if (_match(_TokenType.identifier, 'duration')) {
        _consume();
        _optionalColon();
        duration = _parseValueAsString();
      } else if (_match(_TokenType.identifier, 'icon')) {
        _consume();
        _optionalColon();
        icon = _parseValueAsString();
      } else if (_match(_TokenType.identifier, 'keywords')) {
        _consume();
        _optionalColon();
        keywords = _parseList();
        if (!keywords.contains('EXTERNAL')) keywords.add('EXTERNAL');
      } else {
        // Unknown field, skip key [: val]
        _consume();
        _optionalColon();
        _skipValue();
      }
    }

    _expect(_TokenType.braceClose, '}');

    if (!keywords.contains(category)) {
      keywords.add(category);
    }

    return <String, dynamic>{
      'id': courseId,
      'title': title,
      'description': description,
      'category': category,
      'level': level,
      'duration': duration,
      'icon': icon,
      'keywords': keywords,
      'content': chapters,
    };
  }

  Map<String, dynamic> _parseModule() {
    _expect(_TokenType.identifier, 'module');
    final moduleId = _consume().value;
    _expect(_TokenType.braceOpen, '{');

    String title = moduleId;
    String duration = '15min';
    String content = '';
    final quizQuestions = <Map<String, dynamic>>[];

    while (!_match(_TokenType.braceClose) && _current != null) {
      if (_match(_TokenType.identifier, 'title')) {
        _consume();
        _optionalColon();
        title = _parseValueAsString();
      } else if (_match(_TokenType.identifier, 'duration')) {
        _consume();
        _optionalColon();
        duration = _parseValueAsString();
      } else if (_match(_TokenType.identifier, 'content')) {
        _consume();
        _optionalColon();
        content = _parseValueAsString();
      } else if (_match(_TokenType.identifier, 'quiz')) {
        _consume();
        _expect(_TokenType.braceOpen, '{');
        while (!_match(_TokenType.braceClose) && _current != null) {
          if (_match(_TokenType.identifier, 'question')) {
            quizQuestions.add(_parseQuestion());
          } else {
            _consume();
          }
        }
        _expect(_TokenType.braceClose, '}');
      } else {
        _consume();
        _optionalColon();
        _skipValue();
      }
    }

    _expect(_TokenType.braceClose, '}');

    return <String, dynamic>{
      'id': moduleId,
      'title': title,
      'duration': duration,
      'content': content,
      if (quizQuestions.isNotEmpty) 'quiz': quizQuestions,
    };
  }

  Map<String, dynamic> _parseQuestion() {
    _expect(_TokenType.identifier, 'question');
    final questionText = _consume().value;
    _expect(_TokenType.braceOpen, '{');

    List<String> options = [];
    int correctAnswer = 0;
    String? explanation;

    while (!_match(_TokenType.braceClose) && _current != null) {
      if (_match(_TokenType.identifier, 'options') ||
          _match(_TokenType.identifier, 'choices')) {
        _consume();
        _optionalColon();
        options = _parseList();
      } else if (_match(_TokenType.identifier, 'correctAnswer') ||
          _match(_TokenType.identifier, 'correctIndex')) {
        _consume();
        _optionalColon();
        final val = _consume().value;
        correctAnswer = int.tryParse(val) ?? 0;
      } else if (_match(_TokenType.identifier, 'explanation')) {
        _consume();
        _optionalColon();
        explanation = _parseValueAsString();
      } else {
        _consume();
        _optionalColon();
        _skipValue();
      }
    }

    _expect(_TokenType.braceClose, '}');

    return <String, dynamic>{
      'question': questionText,
      'choices': options,
      'correctIndex': correctAnswer,
      if (explanation != null) 'explanation': explanation,
    };
  }

  void _optionalColon() {
    if (_match(_TokenType.colon)) {
      _consume();
    }
  }

  String _parseValueAsString() {
    if (_match(_TokenType.string) || _match(_TokenType.identifier)) {
      return _consume().value;
    }
    return '';
  }

  List<String> _parseList() {
    _expect(_TokenType.bracketOpen, '[');
    final list = <String>[];
    while (!_match(_TokenType.bracketClose) && _current != null) {
      if (_match(_TokenType.string) || _match(_TokenType.identifier)) {
        list.add(_consume().value);
      }
      if (_match(_TokenType.comma)) {
        _consume();
      }
    }
    _expect(_TokenType.bracketClose, ']');
    return list;
  }

  void _skipValue() {
    if (_match(_TokenType.bracketOpen)) {
      _parseList();
    } else if (_match(_TokenType.braceOpen)) {
      _consume();
      int depth = 1;
      while (depth > 0 && _current != null) {
        if (_match(_TokenType.braceOpen)) depth++;
        if (_match(_TokenType.braceClose)) depth--;
        _consume();
      }
    } else if (_current != null) {
      _consume();
    }
  }
}
