FROM ghcr.io/cirruslabs/flutter:stable

# Install Linux build tools and dependencies pre-packaged to speed up CI/CD
RUN apt-get update -y && \
    apt-get install -y --no-install-recommends \
        clang cmake ninja-build pkg-config \
        libgtk-3-dev liblzma-dev libstdc++-12-dev libsecret-1-dev \
        libfuse2 gnupg ruby ruby-dev build-essential file && \
    gem install --no-document fpm && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
