name: t2decode
version: '1.0.2.4'
summary: Simulateur et boite a outils hors-ligne pour les reseaux et la cybersecurite
description: |
  T2DECODE est une plateforme d'apprentissage hors-ligne pour la cybersecurite et les reseaux.

confinement: strict
base: core22
grade: stable

apps:
  t2decode:
    command: t2decode
    plugs:
      - network
      - network-bind
      - desktop
      - x11

parts:
  t2decode:
    plugin: dump
    source: .
    build-packages:
      - git
      - curl
      - unzip
      - build-essential
      - cmake
      - ninja-build
      - pkg-config
      - libgtk-3-dev
      - liblzma-dev
      - libsecret-1-dev
    override-build: |
      git clone https://github.com/flutter/flutter.git -b stable $CRAFT_STAGE/flutter
      export PATH="$PATH:$CRAFT_STAGE/flutter/bin"
      flutter config --no-enable-swift-package-manager
      flutter pub get
      flutter build linux --release
      mkdir -p $CRAFT_PART_INSTALL
      cp -r build/linux/x64/release/bundle/* $CRAFT_PART_INSTALL/
