name: ClusterFuzzLite PR fuzzing
on:
  pull_request:
    branches: [ main ]

permissions: read-all

jobs:
  PR:
    runs-on: ubuntu-latest
    steps:
    - name: Build Fuzzers
      id: build
      uses: google/clusterfuzzlite/actions/build_fuzzers@v1
      with:
        language: python
        github-token: ${{ secrets.GITHUB_TOKEN }}
        fuzz-seconds: 10
        dry-run: true
